# Generated by Django 4.2.3 on 2024-04-03 04:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="conten",
        ),
    ]
