# Generated by Django 4.2.3 on 2024-04-03 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_content_blog_conten"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="conten",
            new_name="content",
        ),
    ]
